FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .

COPY app/ ./app

EXPOSE 8501

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

CMD ["streamlit", "run", "app/streamlit_app.py", "--server.address=0.0.0.0"]